import React, { useState } from "react";
import StaffRow from "../components/StaffRow";

function StaffPage() {
    const [results, setStaffInfo] = useState([]);
    const getData = () => {
        fetch("https://randomuser.me/api/?results=10")
            .then((response) => response.json())
            .then((response) => {
                setStaffInfo(response.results);
            })
        
            //If error thrown
            .catch((error) => {
                alert("Oops! Something went wrong. Try again.");
                console.error(error);
            });
    };
    
    return (
        <>
            <h2>Get to Know Our Staff</h2>
            <article>
                <p>Please click the button below to see information of ten randomly selected staff members. Their information will be generated by <a href="https://randomuser.me/" target="_blank" rel="noreferrer">Random User API</a>, then appear in the table below.
                </p>
                <p class="staff-button">   
                    <button onClick={getData} value="getTenEmployees">Staff</button>
                </p>
                <br></br>
                <br></br>
                <table class="web-table">
                    <caption>Staff Member Information</caption>
                    <thead>
                        <tr>
                            <th>Photo</th>
                            <th>Name/Email</th>
                            <th>Phone</th>
                            <th>Location</th>
                        </tr>    
                    </thead>
                    <tbody>
                        {/*<!--The randomly generated staff members will appear here-->*/}
                        {results.map((employee, n) => <StaffRow employee={employee} key={n} />)}
                    </tbody>
                </table>
            </article>
        </>
    );

}

export default StaffPage;